# Generated by Django 5.1.2 on 2024-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeMinisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('english_bio', models.CharField(blank=True, max_length=500)),
                ('urdu_bio', models.CharField(blank=True, default='', max_length=500)),
                ('english_achievements', models.CharField(blank=True, default='', max_length=500)),
                ('urdu_achievements', models.CharField(blank=True, default='', max_length=500)),
                ('youtube_link', models.CharField(blank=True, default='', max_length=500)),
                ('background_color', models.CharField(max_length=7)),
                ('term', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prime_ministers_images/')),
            ],
        ),
    ]
